### ISSUE TITLE
используйте менеджер контекста with as

### ISSUE THREAD

**Issue by generalova-kate** [nn-students-2020h1/team_4ever#1]
https://github.com/nn-students-2020h1/team_4ever/blob/172009b2cd28839e05f409ad845a806cf5933b1f/chat_bot_template1.py#L67

**Comment by generalova-kate** [comment]
Как прогресс по баге?

**Comment by igum-natasha** [comment]
Я исправила и все работает

**Comment by generalova-kate** [comment]
тогда нужно закрыть багу :)
